-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.

BEGIN;


ALTER TABLE IF EXISTS public.rides DROP CONSTRAINT IF EXISTS "rides_categoryId_fkey";

ALTER TABLE IF EXISTS public.ticket_uses_ride DROP CONSTRAINT IF EXISTS "ticket_uses_ride_rideId_fkey";

ALTER TABLE IF EXISTS public.ticket_uses_ride DROP CONSTRAINT IF EXISTS "ticket_uses_ride_ticketId_fkey";

ALTER TABLE IF EXISTS public.tickets DROP CONSTRAINT IF EXISTS "tickets_ticketTypeId_fkey";

ALTER TABLE IF EXISTS public.tickets DROP CONSTRAINT IF EXISTS "tickets_userId_fkey";

DROP TYPE IF EXISTS ride_status;
CREATE TYPE ride_status AS ENUM ('open','closed','testing');

DROP TABLE IF EXISTS public."rideCategories";

CREATE TABLE IF NOT EXISTS public."rideCategories"
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "rideCategories_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.rides;


CREATE TABLE IF NOT EXISTS public.rides
(
    id serial NOT NULL,
    "categoryId" integer,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "creationDate" date,
    "durationSeconds" integer,
    "minAge" integer,
    "minHeight" integer,
    status ride_status DEFAULT 'closed',
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT rides_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."ticketTypes";

CREATE TABLE IF NOT EXISTS public."ticketTypes"
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    cost integer,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "ticketTypes_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.ticket_uses_ride;

CREATE TABLE IF NOT EXISTS public.ticket_uses_ride
(
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    "ticketId" integer NOT NULL,
    "rideId" integer NOT NULL,
    CONSTRAINT ticket_uses_ride_pkey PRIMARY KEY ("ticketId", "rideId")
);

DROP TABLE IF EXISTS public.tickets;

CREATE TABLE IF NOT EXISTS public.tickets
(
    id serial NOT NULL,
    "userId" integer NOT NULL,
    "ticketTypeId" integer NOT NULL,
    "boughtAt" timestamp with time zone,
    "validityDate" date,
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "dateOfBirth" date,
    email character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(255) COLLATE pg_catalog."default",
    "createdAt" timestamp with time zone NOT NULL,
    "updatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.rides
    ADD FOREIGN KEY ("categoryId")
    REFERENCES public."rideCategories" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ticket_uses_ride
    ADD CONSTRAINT "ticket_uses_ride_rideId_fkey" FOREIGN KEY ("rideId")
    REFERENCES public.rides (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.ticket_uses_ride
    ADD CONSTRAINT "ticket_uses_ride_ticketId_fkey" FOREIGN KEY ("ticketId")
    REFERENCES public.tickets (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT "tickets_ticketTypeId_fkey" FOREIGN KEY ("ticketTypeId")
    REFERENCES public."ticketTypes" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.tickets
    ADD CONSTRAINT "tickets_userId_fkey" FOREIGN KEY ("userId")
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;

END;